version: "3.8"
services: 
  client:
    build: ./client
    ports: 
      - 80:3000
    restart: unless-stopped
    environment:
      REACT_APP_REDIRECT_URI: http://4.193.194.60
      REACT_APP_SERVER_BASE_URL: http://4.193.194.60:4000
  backend:
    build: ./server
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    ports: 
      - 4000:4000
    env_file:
      - ./server/.env
    environment:
      POSTGRES_DATABASE_URL: postgresql://postgres:514723@postgres:5432/wReflect
      AUTH0_CALLBACK_URL: http://4.193.194.60
      SERVER_URL: http://4.193.194.60:4000
      CLIENT_URL: http://4.193.194.60
  postgres:
    image: postgres:14.8-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 514723
      POSTGRES_DB: wReflect
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: 
