version: "3.8"
services: 
  client:
    build: ./client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/app
  backend:
    build: ./server
    ports: 
      - 4000:4000
    environment:
      POSTGRES_DATABASE_URL: postgresql://postgres:514723@postgres:5432/wReflect
    volumes:
      - ./server:/app
    command: ./docker-entrypoint.sh
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:14.8-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 514723
      POSTGRES_DB: wReflect
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: 
