export default [
  {
    name: "What Went Well, What Didn't Go Well",
    column1: 'Went Well',
    column2: "What Didn't Go Well",
    column3: '',
    column4: '',
    column5: '',
  },
  {
    name: 'Mad, Sad, Glad',
    column1: 'Mad',
    column2: 'Sad',
    column3: 'Glad',
    column4: '',
    column5: '',
  },
  {
    name: 'Start, Stop, Continue',
    column1: 'Start',
    column2: 'Stop',
    column3: 'Continue',
    column4: '',
    column5: '',
  },
  {
    name: 'Went Well, To Improve, Action Items',
    column1: 'Went Well',
    column2: 'To Improve',
    column3: 'Action Items',
    column4: '',
    column5: '',
  },
  {
    name: 'To Discuss, Discussing, Discussed',
    column1: 'To Discuss',
    column2: 'Discussing',
    column3: 'Discussed',
    column4: '',
    column5: '',
  },
  {
    name: 'Liked, Learned, Lacked, Longed For',
    columns: ['Liked', 'Learned', 'Lacked', 'Longed For'],
    column1: 'Liked',
    column2: 'Learned',
    column3: 'Lacked',
    column4: 'Longed For',
    column5: '',
  },
  {
    name: 'Keep, Add, Less, More',
    columns: ['Keep', 'Add', 'Less', 'More'],
    column1: 'Keep',
    column2: 'Add',
    column3: 'Less',
    column4: 'More',
    column5: '',
  },
  {
    name: 'Drop, Add, Keep, Improve',
    columns: ['Drop', 'Add', 'Keep', 'Improve'],
    column1: 'Drop',
    column2: 'Add',
    column3: 'Keep',
    column4: 'Improve',
    column5: '',
  },
  {
    name: 'Strengths, Weaknesses, Opportunities, Threats',
    column1: 'Strengths',
    column2: 'Weaknesses',
    column3: 'Opportunities',
    column4: 'Threats',
    column5: '',
  },
  {
    name: 'Explorer, Shopper, Vacationer, Prisoner',
    column1: 'Explorer',
    column2: 'Shopper',
    column3: 'Vacationer',
    column4: 'Prisoner',
    column5: '',
  },
  {
    name: 'Mistakes, Experiments, Practices, Learnings',
    column1: 'Mistakes',
    column2: 'Experiments',
    column3: 'Practices',
    column4: 'Learnings',
    column5: '',
  },
  {
    name: 'We Do, We Value',
    column1: 'We Do',
    column2: 'We Value',
    column3: '',
    column4: '',
    column5: '',
  },
  // {
  //   name: 'Love, Want, Hate, Learn',
  //   columns: ['Love', 'Want', 'Hate', 'Learn'],
  // },
  // {
  //   name: 'Good, Bad, Better, Best',
  //   columns: ['Good', 'Bad', 'Better', 'Best'],
  // },
  // {
  //   name: 'Key Results, Initiatives, Objectives',
  //   columns: ['Key Results', 'Initiatives', 'Objectives'],
  // },
  // {
  //   name: 'Happy, Meh, Sad',
  //   columns: ['Happy', 'Meh', 'Sad'],
  // },
  // {
  //   name: 'Rose, Bud, Thorn',
  //   columns: ['Rose', 'Bud', 'Thorn'],
  // },
  // {
  //   name: 'Hopes, Fears',
  //   columns: ['Hopes', 'Fears'],
  // },
];

export const columnActionTrackerDefault = [
  {
    name: 'Open',
    index: '1',
    key: 'NEW',
  },
  {
    name: 'In Progress',
    index: '2',
    key: 'IN_PROGRESS',
  },
  {
    name: 'Closed',
    index: '3',
    key: 'DONE',
  },
  {
    name: 'Rejected',
    index: '4',
    key: 'REJECTED',
  },
];
